version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-srv
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_DB_URL: jdbc:mysql://mysql:3306/events-db
      SPRING_DB_USERNAME: root
      SPRING_DB_PASSWORD: mysql
      SPRING_JPA_DDL_AUTO: none
    ports:
      - "8080:8080"
    networks:
      - network

  mysql:
    image: mysql:8.0
    container_name: events-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: events-db
    ports:
      - "3306:3306"
    networks:
      - network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  sonarqube:
    container_name: sonarqube
    image: sonarqube
    restart: always
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube-db
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - network

  postgres:
    image: postgres:15
    restart: always
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network

  redis:
    image: redis:latest
    container_name: events-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - network
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  postgres_data:
  redis_data:
  mysql_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:

networks:
  network:
    driver: bridge