name: Events Application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21

            - name: Run coverage
              run: mvn clean test jacoco:report
              env:
                SPRING_PROFILES_ACTIVE: test

            - name: Generate Badge
              uses: cicirello/jacoco-badge-generator@v2
              with:
                jacoco-csv-file: target/site/jacoco/jacoco.csv
                generate-coverage-badge: true

            - name: Commit Badge
              run: |
                git config --global user.name "github-actions"
                git config --global user.email "github-actions@github.com"
                git add .github/badges/*.svg
                git commit -m "Updating coverage badges"
                git push


    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21
                
            - name: Run unit test
              run: SPRING_PROFILES_ACTIVE=test mvn test
              env:
                SPRING_PROFILES_ACTIVE: test

            - name: Upload test logs if failed
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: surefire-reports-unit
                path: target/surefire-reports/*.txt

    integration-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21

            - name: Run integration test
              run: SPRING_PROFILES_ACTIVE=test mvn verify
              env:
                SPRING_PROFILES_ACTIVE: test

            - name: Upload test logs if failed
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: failsafe-reports-unit
                path: target/failsafe-reports/*.txt
        
    build:
        runs-on: ubuntu-latest
        needs: 
          - unit-test
          - integration-test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21

            - name: Build project
              run: mvn clean install -DskipTests
              env:
                SPRING_DATASOURCE_URL: ${{ secrets.SPRING_FLYWAY_ENABLE }}
                SPRING_PROFILES_ACTIVE: production

            - name: Login Docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build Docker image
              run: docker build -t dvargas42/events-srv .

            - name: Publish image
              run: docker push dvargas42/events-srv
    deploy:
        runs-on: self-hosted         
        needs: build
        steps:
            - name: Create Docker network
              run: docker network inspect events-network >/dev/null 2>&1 || docker network create events-network
                
            - name: Pull APP image from DockerHub
              run: docker pull dvargas42/events-srv:latest
            
            - name: Remove old APP container
              run: docker rm -f events-app || true

            - name: Run APP container
              run: docker run -d --name events-app --network events-network -p 8080:8080 -e SPRING_DB_URL=${{secrets.SPRING_DB_URL}} -e SPRING_DB_USERNAME=${{secrets.SPRING_DB_USERNAME}} -e SPRING_DB_PASSWORD=${{secrets.SPRING_DB_PASSWORD}} -e OPENAI_API_KEY='${{secrets.OPENAI_API_KEY}}' -e SPRING_MAIL_PASSWORD='${{secrets.SPRING_MAIL_PASSWORD}}' -e SPRING_MAIL_USERNAME='${{secrets.SPRING_MAIL_USERNAME}}' -e SPRING_REDIS_HOST=events-redis -e SPRING_REDIS_USER=${{secrets.SPRING_REDIS_USER}} -e SPRING_REDIS_PASSWORD=${{secrets.SPRING_REDIS_PASSWORD}} -e SPRING_REDIS_PORT=6379 dvargas42/events-srv:latest
