name: Events Application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21
                
            - name: Run unit test
              run: SPRING_PROFILES_ACTIVE=test mvn test
              env:
                SPRING_PROFILES_ACTIVE: test

            - name: Upload test logs if failed
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: surefire-reports-unit
                path: target/surefire-reports/*.txt

    integration-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21

            - name: Run integration test
              run: SPRING_PROFILES_ACTIVE=test mvn verify
              env:
                SPRING_PROFILES_ACTIVE: test

            - name: Upload test logs if failed
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: failsafe-reports-unit
                path: target/failsafe-reports/*.txt
        
    build:
        runs-on: ubuntu-latest
        needs: 
          - unit-test
          - integration-test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21

            - name: Build project
              run: mvn clean install -DskipTests
              env:
                SPRING_DATASOURCE_URL: ${{ secrets.SPRING_FLYWAY_ENABLE }}
                SPRING_PROFILES_ACTIVE: production

            - name: Login Docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build Docker image
              run: docker build -t dvargas42/events-srv .

            - name: Publish image
              run: docker push dvargas42/events-srv
    deploy:
        runs-on: self-hosted         
        needs: build
        steps:
            - name: Pull image DockerHub
              run: docker pull dvargas42/events-srv:latest
            
            - name: Remove old container
              run: docker rm -f events-app

            - name: Run Docker container
              run: docker run -d -p 8080:8080 -e SPRING_DB_URL=${{secrets.SPRING_DB_URL}} -e SPRING_DB_USERNAME=${{secrets.SPRING_DB_USERNAME}} -e SPRING_DB_PASSWORD=${{secrets.SPRING_DB_PASSWORD}} --name events-app dvargas42/events-srv
