name: Events Application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            redis:
              image: redis
              ports:
                - 6379:6379
              options: >-
                --health-cmd "redis-cli ping"
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21
            - name: Run teste
              run: mvn test
              env:
                SPRING_PROFILES_ACTIVE: test
                SPRING_REDIS_HOST: localhost
                SPRING_REDIS_PORT: 6379
                SPRING_REDIS_USER: redis
                SPRING_REDIS_PASSWORD: redis
            
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                distribution: temurin
                java-version: 21

            - name: Build project
              run: mvn clean install -DskipTests
              env:
                SPRING_DATASOURCE_URL: ${{ secrets.SPRING_FLYWAY_ENABLE }}
                SPRING_PROFILES_ACTIVE: production

            - name: Login Docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build Docker image
              run: docker build -t dvargas42/events-srv .

            - name: Publish image
              run: docker push dvargas42/events-srv
              
